message(STATUS "include all files: submodule-test project")
message(STATUS "Current dir: ${CMAKE_CURRENT_LIST_DIR}")

set(SUBMODULE_TEST_PROJECT_PATH ${CMAKE_CURRENT_LIST_DIR}/..)
set(SUBMODULE_TEST_INCLUDE_PATH "${SUBMODULE_TEST_PROJECT_PATH}/include")
set(SUBMODULE_TEST_SOURCE_PATH "${SUBMODULE_TEST_PROJECT_PATH}/src")

set(SUBMODULE_TEST_INCLUDE_FILES 
    "${SUBMODULE_TEST_INCLUDE_PATH}/submodule-test/somelib.h"
    )

set(SUBMODULE_TEST_SOURCE_FILES
    "${SUBMODULE_TEST_SOURCE_PATH}/somelib.cpp"
    )
