message(STATUS "include all files: submodule-test project")

set(SUBMODULE_TEST_PROJECT_PATH "..")
set(SUBMODULE_TEST_INCLUDE_PATH "${SUBMODULE_TEST_PROJECT_PATH}/include/submodule-test")
set(SUBMODULE_TEST_SOURCE_PATH "${SUBMODULE_TEST_PROJECT_PATH}/src")

set(SUBMODULE_TEST_INCLUDE_FILES 
    "${SUBMODULE_TEST_INCLUDE_PATH}/somelib.h"
    )

set(SUBMODULE_TEST_SOURCE_FILES
    "${SUBMODULE_TEST_SOURCE_PATH}/somelib.cpp"
    )
